name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-workflow:
      uses: ./.github/workflows/reuseable.yml
      with:
        who-to-greet: "hannehue"
  
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]

    steps:
    - name: tell current time
      run: echo "Time was ${{needs.call-workflow.outputs.curent-time}}"
    